'''
This code generates language_info.json. The content can be extended over time.
    1. Specify languages that appear in the results
    2. Specify aliases, e.g., Mandarin and Putonghua
    3. Specify implications between languages, e.g., Cantonese/Mandarin -> Chinese
'''

import pandas as pd

language = ['cantonese',
            'chinese',
            'dutch',
            'english',
            'french',
            'german',
            'hindi',
            'indonesian',
            'italian',
            'japanese',
            'korean',
            'malay',
            'mandarin',
            'nepali',
            'polish',
            'russian',
            'spanish',
            'tagalog',
            'thai',
            'urdu',
            'vietnamese']
aliases = [[],
           [],
           [],
           [],
           [],
           [],
           [],
           [],
           [],
           [],
           [],
           ['malaysian'],
           ['mandarin chinese', 'putonghua'],
           [],
           [],
           [],
           [],
           [],
           [],
           [],
           []]
implications = [['chinese'],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                ['chinese'],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                []]
pd.DataFrame({'language': language,
              'aliases': aliases,
              'implications': implications}).to_json("language_info.json", orient='records')
